name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Shell Runner Build sublime-package
      run: |
        bash ./build.sh

    - name: Upload sublime-package
      uses: actions/upload-artifact@v2-preview
      with:
        path: ./dist/Rego.sublime-package
